### ISSUE TITLE
undefined symbol: g_thread_init

### ISSUE THREAD

**Issue by bmatusiak** [yue/node-gui#12]
Waf: Leaving directory `/home/bmatusiak/Desktop/gui/node_modules/gui/build'
'build' finished successfully (21.659s)
Waf: Entering directory`/home/bmatusiak/Desktop/gui/node_modules/gui/build'
- installing build/Release/gui.node as /home/bmatusiak/.node_libraries/gui.node
  Waf: Leaving directory `/home/bmatusiak/Desktop/gui/node_modules/gui/build'
  'install' finished successfully (0.141s)
  gui@0.0.1 ./node_modules/gui
  bmatusiak@brad-work-linux:~/Desktop/gui$ node
  > var gui = require ('gui');
  node: symbol lookup error: /home/bmatusiak/.node_libraries/gui.node: undefined symbol: g_thread_init
  bmatusiak@brad-work-linux:~/Desktop/gui$

**Comment by zcbenz** [comment]
Closing since this project is no longer maintained.
