### ISSUE TITLE
node-waf: not found

### ISSUE THREAD

**Issue by 190n** [yue/node-gui#18]
I'm trying to install this for the first time, on Debian 8. I installed all the necessary packages (build-essential and libgtk2.0-dev).

I'm using Node 0.12.4 and npm 2.11.1.

I get the following error:

```
npm WARN package.json @ No description
npm WARN package.json @ No repository field.
npm WARN package.json @ No README data
npm WARN package.json @ No license field.
|
> gui@0.0.1 preinstall /home/ben/code/gui/test/node_modules/gui
> node-waf configure

sh: 1: node-waf: not found
npm ERR! Linux 3.16.0-4-amd64
npm ERR! argv "node" "/usr/bin/npm" "install" "--save" "gui"
npm ERR! node v0.12.4
npm ERR! npm  v2.11.1
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! gui@0.0.1 preinstall: `node-waf configure`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the gui@0.0.1 preinstall script 'node-waf configure'.
npm ERR! This is most likely a problem with the gui package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-waf configure
npm ERR! You can get their info via:
npm ERR!     npm owner ls gui
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ben/code/gui/test/npm-debug.log
```

My npm-debug.log is [here](https://gist.github.com/190n/c7f8803bf91fe4fcf1e5).

**Comment by skibz** [comment]
@190n 
`node-waf` has been replaced by `node-gyp`, i believe
if you're able to find the line in source code where `node-waf configure` is invoked, you can try changing it to `node-gyp rebuild`

**Comment by cancerberoSgx** [comment]
I tried the following commands but they fail:
node-waf configure build install
node-gyp rebuild

Please please do support node-gyp since node-waf is no longer supported and from node 0.8. This basically makes this project unusable

**Comment by zcbenz** [comment]
Closing since this project is no longer maintained.
