### ISSUE TITLE
Problems with painter.

### ISSUE THREAD

**Issue by AnXPyDev** [yue/node-gui#21]
I have encountered an issue
The painter object that is passed by Container into the onDraw event doesn't have the methods drawImage and drawCanvas, which are listed as painter methods in the docs.
I tried to install the module directly from github too but still doesnt work.

My code: https://pastebin.com/0dZTy05W

**Comment by cancerberoSgx** [comment]
Something similar happened to me recently when playing with hearth.js example, https://github.com/yue/yue-sample-apps/blob/master/floating_heart/js/heart.js  - I'm just knowing this awesome library and the problem didn't happen anymore  - there I remember being thrown setFillColor is not a function and remember the code was OK . I also was trying to print the native object  before anything else - I rollback the code as the example is and it start working again - no idea why, perhaps n internal collation of names or some problem with terminal IO. Didn't happened again but I'm just starting w the API and copying from examples so... 

Also you could `node --inspect-brk program.js` and debug the scope variables to get better idea. good look.

**Comment by zcbenz** [comment]
For issues on the library itself, please open issues at https://github.com/yue/yue/issues.
