### ISSUE TITLE
Any thoughts on hiding app in dock?

### ISSUE THREAD

**Issue by JacobBovee** [yue/node-gui#25]
I've scoured the documentation and can't seem to find anything that would enable me to hide the application in the dock similar to Electrons app.dock.hide(). Any thoughts on how that could be enabled? Thank you for the work on this it's a great project!

**Comment by zcbenz** [comment]
For issues on the library itself, please open issues at https://github.com/yue/yue/issues.

To answer your question, currently there is no API for that.
