### ISSUE TITLE
rendering images as fast as possible

### ISSUE THREAD

**Issue by cancerberoSgx** [yue/node-gui#27]
I'm playing to build an image-processor like application and so far I'm able to render a png/jpg from memory and I wonder how hard would be adding support to render raw image data, like in HTMLImageData or ImageMagick's .rgba files?. In general processing libraries / surfaces work with this format so there's no need to encode/decode on each frame. In my case I plan to filter video in real time so this would be important... Notice that painting pizel per pixel is also not viable here. I suspect Node/chrome should have already an API for this(like putImageData in CanvasContext2d) ? Thanks keep it up- the library is awesome the APII is also very good and delivering binaries should encourage users! :)

**Comment by zcbenz** [comment]
For issues on the library itself, please open issues at https://github.com/yue/yue/issues.

On your question, I'm not sure about the answer since I have not done any benchmark and it would depend on each platform, but adding support for raw images would be a good feature.
